### PR TITLE
fix: [#6] Export PDFs with unicode characters greater than 0x7f

### LINKED ISSUE #6: Report export in PDF format not working anymore
As per @clairelema description:

> To reproduce, run a report, export as PDF. TR lets your save but in fact no file is saved.

### PR DESCRIPTION
**Pull request by ursjoss**
Resolves #6

## Summary

This PR resolves one root cause that could lead to PDF exports aborting silently (no direct feedback to the user, stack trace in the log files): Unicode characters greater than 0x7f that are wrongfully escaped. When passed to JasperReports as xml source for conversion to PDF, JasperReports `JRXmlUtils` would abort parsing it with the `SAXParseException` wrapped into the `JRException`.

apache commons-utils-3.1 and later do not escape such unicode characters (by default). The `StringEscapeUtils` were later extracted into it's own library apache commons-text. We're using this class from version 1.9.

### CODE REVIEW

**Comment by ursjoss** [comment]
How to reproduce:
- download attached ThinkingRock transaction file with two tasks in it (test6.zip -> test6.trx) and open it available to your ThinkingRock instance
  [test6.zip](https://github.com/thinkingrock-gtd/tr-pc/files/7641512/test6.zip)
- With the unpached version, try to export from Menu Reports -> Actions: Do ASAP. Confirm the dialog and observe that nothing happens
- Check the log files: You'll see the stack trace with a fatal error with an invalid character reference in a temporary document Actions.xml passed to JasperReport
- Delete the task with problems and observe the export works as expected for the second tasks without problems
- Launch ThinkingRock from the branch of this PR and observe that the export works  with both tasks in.

**Comment by degrown** [comment]
Hello @ursjoss ,
I need some few days, but I didn't forget this issue ok?
BTW, thanks for your effort!

**Comment by ursjoss** [comment]
> Hello @ursjoss , I need some few days, but I didn't forget this issue ok?

No problem at all. In case you have already checked out the branch from this PR, please delete it and do it from scratch, I just rebased the PR on top of main (which is currently a copy of master).

**Comment by ursjoss** [comment]
@degrown Let me know if I can help you bootstrap the project to test the PR.

BTW: This PR only addresses the PDF export. There are several smaller and bigger issues to collect in separate tickets and tackle in different pull requests.

**Comment by ursjoss** [comment]
@degrown Ping

**Comment by degrown** [comment]
As wrote [here](https://github.com/thinkingrock-gtd/tr-discuss-governance/discussions/11#discussioncomment-1801704), I'm not able for now to test anything you do on my only platform (OSX); other than that, this is my work computer so I don't want also to mess up deeply. (btw: I've just upgraded to Mavericks, macOS 11.3, and jdk 8 was thrown away. I've recovered since that, but I think we have to fully support JVM 11+ sooner than later)

**Comment by johandersson** [comment]
Hi, I could not run this pull request branch for issue #8 neither under Java 11 nor 17.

I can't find an exception in the logs. Only the warnings "**Could not load definitions from resource net/sf/antcontrib/antcontrib.properties. It could not be found."** and

**"No such dir .../tr-pc-main/modules/au.com.trgtd.tr.resource/test/unit/src;
should not define test deps".**

**Comment by ursjoss** [comment]
@johandersson Thanks for starting with this. I pasted some instructions on how I managed to fiddle my environment together to work with thinking rock from sources, see [here](https://github.com/thinkingrock-gtd/tr-pc/discussions/23). Let me know if it helps. The notes certainly need some care and improvement. As stated there, I had no prior experience with either Netbeans nor ant-projects, so any informed help/knowledge will be highly appreciated.

I will also try to replicate the steps on a different computer to see where we lack some steps in the instructions.

**Comment by johandersson** [comment]
I have Java experience but very little Netbeans experience unfortunately.

I tried to ant-build with the ant jar in java share dir, but I got:

BUILD FAILED
/home/.../tr-pc/tr-pc/build.xml:5: The following error occurred while
executing this line:
/home/...tr-pc/tr-pc/nbproject/build-impl.xml:42: Cannot find NetBeans
build harness.
Check that nbplatform.default.netbeans.dest.dir and
nbplatform.default.harness.dir are defined.
On a developer machine these are normally defined in
${user.properties.file}=${netbeans.user}/build.properties
but for automated builds you should pass these properties to Ant
explicitly.
You may instead download the harness and platform:
-Dbootstrap.url=.../tasks.jar -Dautoupdate.catalog.url=.../updates.xml


Den mån 12 dec. 2022 kl 18:22 skrev Urs Joss ***@***.***>:

**Comment by ursjoss** [comment]
@johandersson I have been able to reproduce your situation. It seems that opening the project in Netbeans once resolves those symptoms. I have been able to build the project using `ant build` only after I opened the project in Netbeans once.

**Comment by johandersson** [comment]
I managed to get it running. I confirmed that this fix worked. The special character printed as a square on the report, but it appeared.

**Comment by ursjoss** [comment]
@johandersson thank you for testing and confirming this. It's great to have you and @RadoslavCap contributing as well.

**Pull request merged**
