### PR TITLE
refactor: Diamond operator

### PR DESCRIPTION
**Pull request by ursjoss**

### CODE REVIEW

**Comment by RadekCap** [comment]
I've got an impressing "the faster I do PR review, the faster is Urs producing another one" 😃

**Comment by ursjoss** [comment]
> I've got an impressing "the faster I do PR review, the faster is Urs producing another one" smiley

@RadekCap Yeah, sorry for that. Turns out it looks like a pull system with an initial WIP limit of two.

@johandersson If you have the time and interest, please don't hesitate to also contribute with review or PRs, we could need your contribution...

**Comment by RadekCap** [comment]
> @RadekCap Yeah, sorry for that. Turns out it looks like a pull system with an initial WIP limit of two.

Not at all. Continue. It's good. Go on please.

**Review by RadekCap — APPROVED** [review]
lgtm

Application is running properly. Thank you.

**Pull request merged**
