### PR TITLE
refactor: Use StringBuilder over StringBuffer and improve usage

### PR DESCRIPTION
**Pull request by ursjoss**
A house-keeping PR: Use StringBuilder instead of StringBuffer (faster) and avoid String concatenation by using chained appends instaead of `+`.

Expected to have a minor positive effect on memory consumption and perforrmance.

Note: I applied Netbeans refactorings on Warnings in Netbeans - except for the second commit, where a manual refactoring was needed to pull out the ternary if logic inside the append method and only call the append method (w/o string concatenation) when the relevant value is not null.

### CODE REVIEW

**Review by RadekCap — APPROVED** [review]
Good to go.

Application load seem to be longer than in the previous version. Escpecially in between splash screen disappearing and full UI loading. There is simple quite long gap when nothing is displayed. I didn't notice it previously.

**Comment by ursjoss** [comment]
Thanks @RadekCap . I didn't notice an increase in the startup time so far but will investigate it as well. Are you saying this came with this PR or just in general?

**Comment by ursjoss** [comment]
@RadekCap I did a few tests with the new version released from current main and I don't find any particular regressions in startup time from the second launch onwards. It may be that on the first run, the netbeans update mechnism (checking for updated modules) may not profit from caching, as the cache-ttl was reached and new checks are actually required.

If you find consistent delays with your version, please open a new ticket for it, so we can investigate that there.

**Comment by RadekCap** [comment]
It isn't necessary to open a ticket now I think.

I was just observing the application and mentioned a gap in between closed splash screen and opening the full UI. I've just checked it on previous version and it was there probably always. Usually I run the application, switch the context and return back after a while. During the testing I had a full focus on a startup and repeated startup so it kicked me directly.

**Pull request merged**
