### PR TITLE
fix: [#59] Adjust URLs from http to https where feasible

### PR DESCRIPTION
**Pull request by ursjoss**
Continuation of #60, where changing the URL for message retrieval from `http` to `https` actually fixed the functionality.

Here, we continue to apply this pattern. Also migrating some older URLs of avente (www.thinkingrock.com.au - which is not reachable via https and is actually relayed to https://trgtd.com.au).

Note: The Jasper report source files (jrxml) are also affected, but the change will not be user visible, as we need to compile them to the jasper files. As the jasper library is very old, we should upgrade that first (to be addressed in #62).

The class `VersionChecker` contains a hardcoded URL that used to relay to an article on the ThinkingRock home-page, which is not accessible anymore. I replaced it with a link to the the download page for now. We can later figure out what the best option could be.

### CODE REVIEW

**Review by RadekCap — APPROVED** [review]
The update functionality seems to be working, with no issues by quick testing.

Good to go.

**Comment by RadekCap** [comment]
Hmmm, I can see my review approval doesn't count into the required approvals. 

@ursjoss Should I open a new issue or are you going to investigate it?

**Comment by ursjoss** [comment]
> Hmmm, I can see my review approval doesn't count into the required approvals.
> 
> @ursjoss Should I open a new issue or are you going to investigate it?

Hi @RadekCap Thanks for the review. I'll investigate that. I'll merge now bypassing the branch protection for this one though.

**Comment by ursjoss** [comment]
@degrown That's good to know - I didn't think of going to the web archive. I paste here the screenshot for future reference:
image
image
image

**Comment by ursjoss** [comment]
With the changes in this PR, it would show https://www.trgtd.com.au/index.php/download-versions.

If we want to change that, we can create another ticket for it.

**Pull request merged**
