### PR TITLE
fix: [#9] Switching between action tabs show tasks without throwing

### LINKED ISSUE #9: IndexOutOfBoundsException: Invalid range
When launching TrhinkingRock from current main, switching between different action tabls may fail with an `IndexOutOfBoundsException: Invalid Range`. From a user perspective, the newly selected tab will be empty. In many cases, selecting another tab and re-selecting the one that initially failed will result in a tab that properly shows the tasks from that tab.

In fact toggling between two different tabs may alternate between tasks shown and now shown (with the error thrown).

<details><summary>Sample Stacktrace</summary>
<pre>
WARNING [org.openide.windows.WindowManager]: [Winsys] TopComponent au.com.trgtd.tr.view.actns.screens.ReviewActionsTopComponent throws runtime exception from its componentShowing() method.
Please repair it!
java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.rowsDeleted(DefaultRowSorter.java:891)
	at org.jdesktop.swingx.sort.DefaultSortController.rowsDeleted(DefaultSortController.java:398)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4279)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4123)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1529)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at ca.odell.glazedlists.swing.EventTableModel.listChanged(EventTableModel.java:211)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter$ListEventFormat.fire(ListEventAssembler.java:781)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter$ListEventFormat.fire(ListEventAssembler.java:773)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher$SubjectAndListener.firePendingEvent(SequenceDependenciesEventPublisher.java:445)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher.fireEvent(SequenceDependenciesEventPublisher.java:344)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter.fireEvent(ListEventAssembler.java:767)
	at ca.odell.glazedlists.event.ListEventAssembler$AssemblerHelper.commitEvent(ListEventAssembler.java:416)
	at ca.odell.glazedlists.event.ListEventAssembler.commitEvent(ListEventAssembler.java:249)
	at ca.odell.glazedlists.BasicEventList.clear(BasicEventList.java:193)
	at au.com.trgtd.tr.view.actns.screens.ReviewActionsPanel.resetModel(ReviewActionsPanel.java:555)
	at au.com.trgtd.tr.view.actns.screens.ReviewActionsTopComponent.componentShowing(ReviewActionsTopComponent.java:223)
[catch] at org.openide.windows.WindowManager.componentShowing(WindowManager.java:314)
	at org.netbeans.core.windows.WindowManagerImpl.componentShowing(WindowManagerImpl.java:1226)
	at org.netbeans.core.windows.view.DefaultView.changeGUI(DefaultView.java:143)
	at org.netbeans.core.windows.ViewRequestor.dispatchRequest(ViewRequestor.java:250)
	at org.netbeans.core.windows.ViewRequestor.processRequest(ViewRequestor.java:226)
	at org.netbeans.core.windows.ViewRequestor.postRequest(ViewRequestor.java:164)
	at org.netbeans.core.windows.ViewRequestor.scheduleRequest(ViewRequestor.java:102)
	at org.netbeans.core.windows.Central.addModeOpenedTopComponent(Central.java:766)
	at org.netbeans.core.windows.ModeImpl.addOpenedTopComponent(ModeImpl.java:333)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpenAtTabPosition(WindowManagerImpl.java:1295)
	at org.netbeans.core.windows.WindowManagerImpl.topComponentOpen(WindowManagerImpl.java:1252)
	at org.openide.windows.TopComponent.open(TopComponent.java:472)
	at org.openide.windows.TopComponent.open(TopComponent.java:452)
	at au.com.trgtd.tr.view.actns.RAAction$2.run(RAAction.java:128)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</pre>
</details>

## How to reproduce

- Open ThinkingRock from main (without the code changes from this PR).
- Make sure to open a data file with multiple tasks and ensure you have more than one action tab
- Open the actions view and jump between different tabs. To observe the problem 
  - look for the exception in the logs or in system out
  - see that the actions are not always listed in the different action tabs.
- Open Thinking rock from the associated PR and do the same steps to see that
  - there is no such error in the logs/system out and
  - jumping between action tabs will always show the actions as expected.

### PR DESCRIPTION
**Pull request by ursjoss**
resolves #9

Use Java 11 to test this PR (Java 17 compatibility comes with #17 only). Alternatively, it can be tested with the code of PR #21, which runs with java 17 as well but contains many other fixes. I would want to merge this in isolation to keep the PRs a little more coherent.

### CODE REVIEW

**Comment by degrown** [comment]
As I wrote [here](https://github.com/thinkingrock-gtd/tr-discuss-governance/discussions/11#discussioncomment-1801704), for now I don't have an easy way to review the pull requests.  
But: in this case the fix seems clean and quite simple, so it's a +1 from me

**Comment by ursjoss** [comment]
To reproduce the issue, you can use the sample file I had uploaded to #8 in [this comment](https://github.com/thinkingrock-gtd/tr-pc/pull/8#issuecomment-984553989).

Open the file with the code from `main`, access the `Action Screens`, select `Do ASAP`, observe there is no task listed. Then switch to e.g. the `Delegated` tab and back to `Do ASAP` - observe there are now two tasks.

Toggling back and forth between the two tabs will alternatingly show the two tasks in `Do ASAP` - or not.

Opening the tool from the PR branch will show the two tasks every time you access `Do ASAP`.

**Comment by RadoslavCap** [comment]
Unfortunately, these code changes don't fix the issue.

Switching tabs on the given sample data file (test6.trx) still throws java.lang.IndexOutOfBoundsException.

Used java and system info:
`>System Info: 
  Product Version         = ThinkingRock 3.7.0
  Operating System        = Linux version 4.18.0-425.3.1.el8.x86_64 running on amd64
  Java; VM; Vendor        = 11.0.17; OpenJDK 64-Bit Server VM 11.0.17+8-LTS; Red Hat, Inc.
  Runtime                 = OpenJDK Runtime Environment 11.0.17+8-LTS
  Java Home               = /usr/lib/jvm/java-11-openjdk-11.0.17.0.8-2.el8_6.x86_64
  System Locale; Encoding = en_US (trgtd); UTF-8` 

Stack trace
`java.lang.IndexOutOfBoundsException: Invalid range
	at java.desktop/javax.swing.DefaultRowSorter.rowsDeleted(DefaultRowSorter.java:891)
	at org.jdesktop.swingx.sort.DefaultSortController.rowsDeleted(DefaultSortController.java:398)
	at java.desktop/javax.swing.JTable.notifySorter(JTable.java:4279)
	at java.desktop/javax.swing.JTable.sortedTableChanged(JTable.java:4123)
	at java.desktop/javax.swing.JTable.tableChanged(JTable.java:4400)
	at org.jdesktop.swingx.JXTable.tableChanged(JXTable.java:1529)
	at java.desktop/javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:297)
	at ca.odell.glazedlists.swing.EventTableModel.listChanged(EventTableModel.java:211)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter$ListEventFormat.fire(ListEventAssembler.java:781)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter$ListEventFormat.fire(ListEventAssembler.java:773)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher$SubjectAndListener.firePendingEvent(SequenceDependenciesEventPublisher.java:445)
	at ca.odell.glazedlists.event.SequenceDependenciesEventPublisher.fireEvent(SequenceDependenciesEventPublisher.java:344)
	at ca.odell.glazedlists.event.ListEventAssembler$ListSequencePublisherAdapter.fireEvent(ListEventAssembler.java:767)
	at ca.odell.glazedlists.event.ListEventAssembler$AssemblerHelper.commitEvent(ListEventAssembler.java:416)
	at ca.odell.glazedlists.event.ListEventAssembler.commitEvent(ListEventAssembler.java:249)
	at ca.odell.glazedlists.BasicEventList.clear(BasicEventList.java:193)
	at au.com.trgtd.tr.view.actns.screens.ReviewActionsPanel.resetModel(ReviewActionsPanel.java:555)
	at au.com.trgtd.tr.view.actns.screens.ReviewActionsTopComponent.componentShowing(ReviewActionsTopComponent.java:223)
[catch] at org.openide.windows.WindowManager.componentShowing(WindowManager.java:314)
	at org.netbeans.core.windows.WindowManagerImpl.componentShowing(WindowManagerImpl.java:1226)
	at org.netbeans.core.windows.view.DefaultView.changeGUI(DefaultView.java:143)
	at org.netbeans.core.windows.ViewRequestor.dispatchRequest(ViewRequestor.java:250)
	at org.netbeans.core.windows.ViewRequestor.processRequest(ViewRequestor.java:226)
	at org.netbeans.core.windows.ViewRequestor.postRequest(ViewRequestor.java:164)
	at org.netbeans.core.windows.ViewRequestor.scheduleRequest(ViewRequestor.java:102)
	at org.netbeans.core.windows.Central.setModeSelectedTopComponent(Central.java:732)
	at org.netbeans.core.windows.Central.userActivatedTopComponent(Central.java:1916)
	at org.netbeans.core.windows.view.DefaultView.userSelectedTab(DefaultView.java:674)
	at org.netbeans.core.windows.view.ui.TabbedHandler.stateChanged(TabbedHandler.java:289)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:108)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:94)
	at org.netbeans.core.windows.view.ui.tabcontrol.AbstractTabbedImpl.fireStateChanged(AbstractTabbedImpl.java:498)
	at org.netbeans.core.windows.view.ui.tabcontrol.TabbedAdapter$1.stateChanged(TabbedAdapter.java:56)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:108)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:94)
	at org.netbeans.swing.tabcontrol.plaf.DefaultTabSelectionModel.setSelectedIndex(DefaultTabSelectionModel.java:86)
	at org.netbeans.swing.tabcontrol.plaf.BasicTabDisplayerUI$BasicDisplayerMouseListener.performCommand(BasicTabDisplayerUI.java:756)
	at org.netbeans.swing.tabcontrol.plaf.BasicTabDisplayerUI$BasicDisplayerMouseListener.potentialCommand(BasicTabDisplayerUI.java:745)
	at org.netbeans.swing.tabcontrol.plaf.BasicTabDisplayerUI$BasicDisplayerMouseListener.mousePressed(BasicTabDisplayerUI.java:720)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Review by RadoslavCap — APPROVED** [review]

**Review by RadoslavCap — APPROVED** [review]
The code looks good.

**Pull request merged**
